---

- name: Create database {{ db_name }}
  command: sudo nine-manage-databases database create {{ db_name }} --user={{ db_user }} --password={{ db_pass }}
  register: out

- debug: var=out.stdout_lines