---
- name: Drupal Deploy
  hosts: all
  #become: true

  vars_files:
    - vars/drupal.yml

  vars:
    drupal_deploy: true
    drupal_deploy_repo: "git@gitlab.com:stiv/farmak.git"
    drupal_deploy_version: dev
    drupal_domain: "xyz.devshop.mikestiv.com"
    drupal_deploy_dir: "/var/www/{{ drupal_domain }}"
    drupal_core_path: "{{ drupal_deploy_dir }}/web"
    drupal_deploy_composer_install: true
    drupal_db_user: xyz
    drupal_db_name: xyz
    drupal_db_password: xyz

    drupal_install_site: true
    drupal_site_name: "{{ drupal_domain }}"
    drupal_install_profile: standard
    drupal_site_install_extra_args: []
    drupal_enable_modules: []
    drupal_account_name: admin1
    drupal_account_pass: admin1

    letsencrypt_email: stivaktakis@gmail.com

    # Disable Composer-based codebase setup.
    drupal_build_composer_project: true
    #drupal_build_composer: true
    drupal_composer_dependencies: []
    #drupal_composer_dependencies:
    #  - "drupal/devel:^1.2"
    #  - "drush/drush"

  roles:
    - { role: msti.mysql, tags: mysql }
    - role: geerlingguy.drupal
    - { role: geerlingguy.apache,  tags: apache }
