---
- name: Converge
  hosts: all
  #become: true

  vars_files:
    - vars/main.yml

  vars:
    # Deploy from the Drupal VM Prod example project.
 #   drupal_deploy: true
 #   drupal_deploy_repo: "git@gitlab.com:stiv/farmak.git"
 #   drupal_deploy_version: dev
 #   drupal_deploy_dir: /var/www/farmak
 #   drupal_domain: "farmak.devshop.mikestiv.com"
 #   drupal_deploy_composer_install: true
 #   drupal_db_user: mike
 #   drupal_db_name: mike
 #   drupal_db_password: mike

    # Disable Composer-based codebase setup.
 #   drupal_build_composer_project: true
    #drupal_build_composer: true
 #   drupal_composer_dependencies: []
    #drupal_composer_dependencies:
    #  - "drupal/devel:^1.2"
    #  - "drush/drush"

  pre_tasks:
    - import_tasks: test-setup.yml

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - role: geerlingguy.repo-dotdeb
      when: ansible_distribution == 'Debian'
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.git
    - role: geerlingguy.composer
    - role: geerlingguy.drush
#    - role: geerlingguy.drupal
