---

- hosts: drupal_hosts
  sudo: no

  vars:
    - webroot: /home/www-data/mike-ansible/web
    - approot: /home/www-data/mike-ansible
    - uri: mike-ansible.zehnplus01.nine.ch
    - composer_bin: /home/www-data/bin/composer
    - drush_bin: /home/www-data/bin/drush
    - repo: git@bitbucket.org:zehnplus/mike-test.git
    - branch: master

  roles:
    - drupal