---

- hosts: drupal_hosts
  sudo: no

  vars:
    - db_name: nmd_mike_ansible
    - db_user: nmd_mike_ansible
    - webroot: /home/www-data/mike-ansible/web
    - approot: /home/www-data/mike-ansible
    - uri: mike-ansible.zehnplus01.nine.ch
    - composer_bin: /home/www-data/bin/composer
    - drush_bin: /home/www-data/bin/drush
    - branch: dev


  roles:
    - nine
    - drupal