---

- hosts: drupal_hosts
  sudo: no

  vars:
    - db_name: nmd_mike_ansible
    - db_user: nmd_mike_ansible
    - db_user: nmd_mike_ansible_random_pass

    - soure_db_name: name
    - source_db_user: user
    - source_db_pass: pass

    - approot: /home/www-data/mike-ansible
    - webroot: /home/www-data/mike-ansible/web
    - uri: mike-ansible.zehnplus01.nine.ch
    - composer_bin: /home/www-data/bin/composer
    - drush_bin: /home/www-data/bin/drush
    - repo: git@bitbucket.org:zehnplus/mike-test.git
    - branch: master
    - behat_dir: /home/www-data/mike-ansible/tests

  roles:
    - nine
    - drupal_install
 #   - drupal_setup
 #   - behat_setup